package com.changingpay.tspring.dao;

import com.changingpay.tspring.model.TAuthorityAuthInfo;
import com.changingpay.tspring.model.TAuthorityAuthInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface TAuthorityAuthInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int countByExample(TAuthorityAuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int deleteByExample(TAuthorityAuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int deleteByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int insert(TAuthorityAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int insertSelective(TAuthorityAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    List<TAuthorityAuthInfo> selectByExample(TAuthorityAuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    TAuthorityAuthInfo selectByPrimaryKey(String authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") TAuthorityAuthInfo record, @Param("example") TAuthorityAuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int updateByExample(@Param("record") TAuthorityAuthInfo record, @Param("example") TAuthorityAuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int updateByPrimaryKeySelective(TAuthorityAuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_authority_auth_info
     *
     * @mbggenerated Tue Oct 18 17:05:20 CST 2016
     */
    int updateByPrimaryKey(TAuthorityAuthInfo record);
}